### ISSUE TITLE
Why this term fails to typecheck?

### ISSUE THREAD

**Issue by MaiaVictor** [AndrasKovacs/tcbe#2]
I'm trying to typecheck this term:

    Lam (For Type (For (Var 0) (Var 1))) (Var 0)

Which, if I understand correctly, is equivalent to `λ(p : (∀ (x : *) -> (x -> x))) -> p`. I get a type mismatch error. Why?

**Comment by AndrasKovacs** [comment]
Sorry for confusing notation. `λ(p : (∀ (x : *) -> (x -> x))) -> p` in `Minimal.hs` is written as `(lam "p" (pi "x" star $ "x" ==> "x") $ "p")`  in `RawTerm` or `(Lam (Pi Star $ Pi (Var 0) (Var 0)) $ Var 0)` in `Term`. 

That's because we use de Bruijn levels instead of indices, and also `forAll` is (confusingly, I admit) shorthand for `λ(x : *)` instead of `(x : *)`.

**Comment by MaiaVictor** [comment]
Ahh. Of course. You said right on the post you was using Bruijn levels. Totally my fault for forgetting that. 

Is there any simple way to convert to using bruijn indices (just for the fact I'm used to them), or would it be hard and/or problematic?

**Comment by AndrasKovacs** [comment]
[Added DB indexed version](https://github.com/AndrasKovacs/tcbe/commit/8278ce42e521cd32785c9a3e7e144e0aae24ba02), it's indeed very small change.

**Comment by MaiaVictor** [comment]
Thank you!
